### ISSUE TITLE
Write markdown files with content

### ISSUE THREAD

**Issue by cedricdelpoux** [jonschlinkert/write-yaml#1]
Hi, 
how can I specify a content in the json source object that is not a frontmatter ? I want to generate a markdown file with frontmatter and a content like this : 

```
---
title: myTitle
date: myDate
---
myContent
```

**Comment by jonschlinkert** [comment]
Use [gray-matter](https://github.com/jonschlinkert/gray-matter) for this instead. There is a `.stringify` method that does exactly what you want.

**Comment by cedricdelpoux** [comment]
Perfect, thank you very much
